### ISSUE TITLE
Root directory files not found

### ISSUE THREAD

**Issue by ScottSmith95** [Lukx/gulp-kit#13]
I keep most of my kit partials in a folder in the root directory of my project. Currently, the only way to reference these files from a subdirectory is like so: `../kit-includes/foo.kit`
I would hope there is a way to improve this so I can just specify the root path and gulp-kit picks up the files there (like so: `/kit-includes/foo.kit`).

If this issue needs to be placed upstream, just close this and I'll post it there.

**Comment by lukx** [comment]
Hey @ScottSmith95 ,
thanks for the input.
Honestly, I don't think this can or should be solved in gulpkit, as the place where partial paths are resolved is inside within node-kit (I think)
May I close this remark?

**Comment by ScottSmith95** [comment]
I found this too, here in this discussion Jeremy sets it out pretty clearly, but I'm starting to wonder is gulp-kit isn't letting it resolve root file paths? https://github.com/jeremyworboys/node-kit/issues/18

**Comment by fatso83** [comment]
@ScottSmith95 Could you possibly create a test repo that displays the problem? I need to have a reproducible error to be able to fix anything :)
