### ISSUE TITLE
Transfer ownership of repo

### ISSUE THREAD

**Issue by fatso83** [Lukx/gulp-kit#14]
Hi, ref the discussion in #2 a year or so ago you were looking for maintainer. [I volunteered](https://github.com/Lukx/gulp-kit/issues/2#issuecomment-144856529), but got no response. Are you still looking? If so you can [transfer the repo](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) to me, and I'll take on the maintainership.

**Comment by lukx** [comment]
Sorry, absolutely yes

**Comment by lukx** [comment]
Apparently, you'll have to quickly remove your fork 
What is your NPM user name?

**Comment by lukx** [comment]
Found you on NPM ;-)
I already added you to the collab list in NPM.

**Comment by fatso83** [comment]
Fork removed :-)

**Comment by lukx** [comment]
Transfer requested :-)
Thank you so much for taking over :-)

**Comment by fatso83** [comment]
Thanks :)
