### ISSUE TITLE
Source Map support

### ISSUE THREAD

**Issue by kenguest** [Lukx/gulp-kit#23]
Are there plans to generate sourcemaps ( https://web.dev/articles/source-maps & https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?pli=1#heading=h.1ce2c87bpj24 ) so that when debugging through an assembled file created by gulp-kit the browser/ide knows which smaller file the code came from and opens the correct one at the right line?

Having this would be fantastic.

**Comment by fatso83** [comment]
I'd ask the author of the main dependency for that, as this just wraps it

**Comment by fatso83** [comment]
Meaning Jeremy
https://github.com/jeremyworboys/node-kit

**Comment by kenguest** [comment]
Thanks for such a quick response! Really appreciate it.

I've raised a query there at https://github.com/jeremyworboys/node-kit/issues/20 if anybody's curious ;-)

**Comment by kenguest** [comment]
Thanks for such a quick response! Really appreciate it.
I've raised a query there at https://github.com/jeremyworboys/node-kit/issues/20 if anybody's curious ;-)
